### ISSUE TITLE
Symbolic link

### ISSUE THREAD

**Issue by alen-z** [git-multimail/git-multimail#137]
My .git hook directory is a symbolic link and multimail does not work.

Not sure if this was the problem but I was unable to send reports on post-receive. post-receive contained .py code and --bare repository had multimailhook configuration with mailingList set. Machine has working sendmail binary.

**Comment by mhagger** [comment]
@alen-z: if you push to the repository via the command line, do you see any output from multimail among the git output?

**Comment by alen-z** [comment]
No.

**Comment by moy** [comment]
What happens if you execute the hook directly from the command-line, like

    ./post-receive

?

Are you sure that the symbolic link points to an executable file (if not, you need a chmod +x)?

I just tested and a symbolic link pointing to `git_multimail.py` seems to work for me at least.

**Comment by alen-z** [comment]
Running `./hooks/post-receive` from my `--bare` repo gives me absolutely nothing related to Multimail - which I would say is ok in a way?

My `ls -s` is on hooks directory, not to `git-multimail.py` inside `hooks` directory where `post-receive` lies:
```
config
HEAD
hooks -> /path-to-custom-hooks
index
objects
refs
```

`git-multimail.py` is executable.

`post-receive` contains:
```python
python <<MULTIMAIL
import sys
import os

# If necessary, add the path to the directory containing
# git_multimail.py to the Python path as follows.  (This is not
# necessary if git_multimail.py is in the same directory as this
# script):

LIBDIR = '/path-to-git-multimail'
sys.path.insert(0, LIBDIR)

import git_multimail

# Specify which "git config" section contains the configuration for
# git-multimail:
config = git_multimail.Config('multimailhook')

# Select the type of environment:
try:
    environment = git_multimail.GenericEnvironment(config=config)
    #environment = git_multimail.GitoliteEnvironment(config=config)
except git_multimail.ConfigurationException:
    sys.stderr.write('*** %s\n' % sys.exc_info()[1])
    sys.exit(1)


# Choose the method of sending emails based on the git config:
mailer = git_multimail.choose_mailer(config, environment)

# Read changes from stdin and send notification emails:
git_multimail.run_as_post_receive_hook(environment, mailer)
MULTIMAIL
```

`git config --edit` contains:
```
[multimailhook]
        mailingList = "asd@dummy.com"
```

Maybe because `hooks` directory is symbolic link, Multimail can reach proper git config file? Just a thought.

**Comment by moy** [comment]
Your `post-receive` hook feeds python's stdin with a Python program, hence Git cannot provide the refs on stdin anymore. It does not work, but it's not related to symbolic links. When running `post-receive`, you should either see `No email recipients configured!` or have the script wait for input.

Any reason why you are not running `git_multimail.py` directly? I see nothing specific in your hook, so no reason to write a custom hook. If you insist in writing a custom hook, then write a real python program (`#!/usr/bin/env python`), don't use `<< MULTIMAIL`.

**Comment by alen-z** [comment]
Thank you for fast response.

Our `post-receive` is a combination of bash commands and Python. This is why `<<MULTIMAIL`. I didn't paste the whole file.

So if I combine `#!/bin/bash` shebang and Python, it's a problem?

By
> running `git_multimail.py` directly

you mean `post-receive` should contain code from `git_multimail.py`? This doesn't work for us because we need additional shell commands.

**Comment by moy** [comment]
> you mean post-receive should contain only code from git_multimail.py?

I mean it should be the file `git_multimail.py` (renamed to `post-receive`), or a link to it.

> This doesn't work for us because we need additional shell commands.

Then, just execute it.

    #! /bin/bash
    whatever
    /path/to/git_multimail.py "$@"
    whatever else
    ...

Just be sure that you don't eat stdin within the `whatever` part. Or, if you do so, keep the content of stdin somewhere and feed it to `git_multimail.py`.

**Comment by alen-z** [comment]
Ok, there is a progress. Running `/path/to/git_multimail.py "$@"` from `post-receive`:

```
^CTraceback (most recent call last):
  File "/path/to/git_multimail.py", line 3764, in <module>
    main(sys.argv[1:])
  File "/path/to/git_multimail.py", line 3747, in main
    run_as_post_receive_hook(environment, mailer)
  File "/path/to/git_multimail.py", line 3405, in run_as_post_receive_hook
    for line in sys.stdin:
KeyboardInterrupt
```
This is printed when I stop the script with `Ctrl+C`. Prior to termination, script waits for input.

**Comment by moy** [comment]
Waiting for input is the expected behavior. That's how `post-receive` works. Getting a keyboard interrupt when you press Ctrl+C is expected too ;-).

**Comment by alen-z** [comment]
Update is in previous post.
Kind regards.

**Comment by alen-z** [comment]
bump

Why do I recieve only summary, not diff from the commit?
```
This is an automated email from the git hooks/post-receive script.

azubic pushed a change to branch master
in repository dabar_statistics.

      from  23687a7   multi v1.1
      adds  e70c13a   multi v2

No new revisions were added by this update.

Summary of changes:
 statistics.module |    3 +--
 1 file changed, 1 insertion(+), 2 deletions(-)

--
To stop receiving notification emails like this one, please contact the administrator of this repository.
```
Configuration is in `git config --system -e`:
```
[multimailhook]
        mailingList = "asd@dummy.com"
        emailPrefix = "[foo]"
        from = "dsa@dummy.com"
        commitList = "asd@dummy.com"
        commitEmailFormat = "html"
```
Thank you.

**Comment by moy** [comment]
It's because "No new revisions were added by this update.". I guess you already had a reference to the pushed commits, or the rest of your script added such reference before multimail was run.

Call `git_multimail.py` with `--force-send` to disable new commits detection, or play with multimailhook.refFilter* variables.

**Comment by alen-z** [comment]
Great tip. Moved `/path/to/git_multimail.py "$@"` to the top of `post-receive` before messig up the refs and it works. Until we meet again :D
Props.
