### ISSUE TITLE
 TypeError: a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by Nyakman** [git-multimail/git-multimail#170]
Hello. Im trying to run this script on WinServ2012. But when someone make push to repository they get this: 

> Traceback (most recent call last):
>   File "hooks/post-receive", line 62, in <module>
>      environment = git_multimail.GenericEnvironment(config=config)
>    File "c:\myrep.git\hooks\git_multimail.py", line 3003, in __init__
>      config, 'refchangelist', 'mailinglist',
>    File "c:\myrep.git\hooks\git_multimail.py", line 3027, in _get_recipie
> 
>      lines = config.get_all(name)
>    File "c:\myrep.git\hooks\git_multimail.py", line 629, in get_all
>      env=self.env, keepends=True,
>    File "c:\myrep.git\hooks\git_multimail.py", line 439, in read_git_outp
> 
>      choose_git_command()
>    File "c:\myrep.git\hooks\git_multimail.py", line 429, in choose_git_co
> 
>      read_output(cmd)
>    File "c:\myrep.git\hooks\git_multimail.py", line 456, in read_output
>      stdin=stdin, stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kw
>    File "C:\python3\lib\subprocess.py", line 947, in __init__
>      restore_signals, start_new_session)
>    File "C:\python3\lib\subprocess.py", line 1198, in _execute_child
>      args = list2cmdline(args)
>    File "C:\python3\lib\subprocess.py", line 751, in list2cmdline
>      needquote = (" " in arg) or ("\t" in arg) or not arg
>  TypeError: a bytes-like object is required, not 'str'

git_multimail.py and post-receive are in the same folder.

Path = C:\Program Files\Git\cmd;C:\Program Files\Git\bin;C:\Program Files\Git\libexec\git-core;C:\Program Files\TortoiseGit\bin;C:\python3

**Comment by moy** [comment]
Hi,

Thanks for the detailed report. Unfortunately, my development skills under Windows approach zero (I don't even have a windows machine at hand with Git installed ...). I would welcome patches to support windows, and I would love to have a windows maintainer for git-multimail, but I'm unlikely to fix this bug myself unless you can reproduce it on Linux.

You may try the recipe available here with the latest git_multimail.py: https://github.com/git-multimail/git-multimail/blob/master/doc/troubleshooting.rst#how-to-check-that-git-multimail-is-properly-set-up

**Comment by Nyakman** [comment]
well... its time to migrate on linux 

> $ GIT_MULTIMAIL_CHECK_SETUP=true C:/myrep.git/hooks/git_multimail.py

> Exception 'TypeError' raised. Please report this as a bug to
> https://github.com/git-multimail/git-multimail/issues
> with the information below:
> 
> git-multimail version 1.4.0
> Python version 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32
>  bit (Intel)]
> Traceback (most recent call last):
>   File "C:/myrep.git/hooks/git_multimail.py", line 4185, in main
>     hook_info=hook_info,
>   File "C:/myrep.git/hooks/git_multimail.py", line 3814, in choose_environment
>     env_name = choose_environment_name(config, env, osenv)
>   File "C:/myrep.git/hooks/git_multimail.py", line 3826, in choose_environment_n
> ame
>     env = config.get('environment')
>   File "C:/myrep.git/hooks/git_multimail.py", line 603, in get
>     env=self.env, keepends=True,
>   File "C:/myrep.git/hooks/git_multimail.py", line 439, in read_git_output
>     choose_git_command()
>   File "C:/myrep.git/hooks/git_multimail.py", line 429, in choose_git_command
>     read_output(cmd)
>   File "C:/myrep.git/hooks/git_multimail.py", line 456, in read_output
>     stdin=stdin, stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kw
>   File "C:\python3\lib\subprocess.py", line 947, in __init__
>     restore_signals, start_new_session)
>   File "C:\python3\lib\subprocess.py", line 1198, in _execute_child
>     args = list2cmdline(args)
>   File "C:\python3\lib\subprocess.py", line 751, in list2cmdline
>     needquote = (" " in arg) or ("\t" in arg) or not arg
> TypeError: a bytes-like object is required, not 'str'

**Comment by moy** [comment]
Well, let's be positive and hope some windows developer comes around and help ... I've renamed the issue to make it more likely to catch the attention.

**Comment by moy** [comment]
Another thing you may try: use Python 2.7 instead of Python 3. Encoding issues are different, it may work. Or not.

**Comment by Nyakman** [comment]
Suddenly its work. Thanks for help. Python version 2.7.12
