### ISSUE TITLE
SMTPServerDisconnected Bug

### ISSUE THREAD

**Issue by LovesTha** [git-multimail/git-multimail#181]
Doing as requested by the script :)

remote: Exception 'SMTPServerDisconnected' raised. Please report this as a bug to
remote: https://github.com/git-multimail/git-multimail/issues
remote: with the information below:
remote: 
remote: git-multimail version 1.4.0
remote: Python version 2.7.12 (default, Nov 19 2016, 06:48:10) 
remote: [GCC 5.4.0 20160609]
remote: Traceback (most recent call last):
remote:   File "hooks/post-receive", line 4214, in main
remote:     run_as_post_receive_hook(environment, mailer)
remote:   File "hooks/post-receive", line 3669, in run_as_post_receive_hook
remote:     push.send_emails(mailer, body_filter=environment.filter_body)
remote:   File "hooks/post-receive", line 3626, in send_emails
remote:     rev.recipients,
remote:   File "hooks/post-receive", line 2146, in send
remote:     self.smtp.sendmail(self.envelopesender, to_addrs, msg)
remote:   File "/usr/lib/python2.7/smtplib.py", line 733, in sendmail
remote:     (code, resp) = self.mail(from_addr, esmtp_opts)
remote:   File "/usr/lib/python2.7/smtplib.py", line 481, in mail
remote:     return self.getreply()
remote:   File "/usr/lib/python2.7/smtplib.py", line 368, in getreply
remote:     raise SMTPServerDisconnected("Connection unexpectedly closed")
remote: SMTPServerDisconnected: Connection unexpectedly closed
remote: 
remote: Exception smtplib.SMTPServerDisconnected: SMTPServerDisconnected('please run connect() first',) in <bound method SMTPMailer.__del__ of <__main__.SMTPMailer object at 0x7fc51b8f08d0>> ignored

As I see a vaguely similar bug was closed for not enough info

config file relevant section:
[multimailhook]
        mailinglist = garethp@sample.com
        envelopesender = garethp@sample.com
        smtpserver = mail.sample.com
        smtpuser = garethp@sample.com
        smtppass = <my valid password>
        smtpencryption = tls
        mailer = smtp
[multimail]
        reponame = GPSat Linux Repo
        commitemailformat = html
        administrator = Gareth

This happened when I was attempting to push a new branch with a several commits in it. I did recieve 4 emails, a branch created one, and 01 to 03/18 for each of the patches.

**Comment by LovesTha** [comment]
It's happened a second time, again when pushing a new branch, this time with 24 commits in the new branch. Again the new branch and 3 emails were received.

**Comment by LovesTha** [comment]
This time I had smtp debug level set higher, the important and I suspect suficient information is:
remote: reply: '250 OK id=1d5PXw-002wMt-1M\r\n'
remote: reply: retcode (250); Msg: OK id=1d5PXw-002wMt-1M
remote: data: (250, 'OK id=1d5PXw-002wMt-1M')
remote: send: 'AUTH PLAIN sniped==\r\n'
remote: reply: '503-already authenticated\r\n'
remote: reply: '503 Too many syntax or protocol errors\r\n'

Attempting to reauthenticate for each message apparently isn't acceptable to the mail server I'm using.

**Comment by LovesTha** [comment]
Attempted a fix with pull request https://github.com/git-multimail/git-multimail/pull/182
