### ISSUE TITLE
Receiving this message sometimes: Exception 'timeout' raised. Please report this as a bug to ..  when pushing to the repository

### ISSUE THREAD

**Issue by hbala2** [git-multimail/git-multimail#185]
I am getting this message when doing a push to the repository sometimes. Since its a post-receive hook, the push is successful, but the e-mail notifications are not sent out.

remote:
remote: Exception 'timeout' raised. Please report this as a bug to
remote: https://github.com/git-multimail/git-multimail/issues
remote: with the information below:
remote:
remote: git-multimail version 1.4.0
remote: Python version 2.6.6 (r266:84292, May 22 2015, 08:34:51)
remote: [GCC 4.4.7 20120313 (Red Hat 4.4.7-15)]
remote: Traceback (most recent call last):
remote:   File "hooks/post-receive", line 4214, in main
remote:     run_as_post_receive_hook(environment, mailer)
remote:   File "hooks/post-receive", line 3669, in run_as_post_receive_hook
remote:     push.send_emails(mailer, body_filter=environment.filter_body)
remote:   File "hooks/post-receive", line 3596, in send_emails
remote:     rev.recipients,
remote:   File "hooks/post-receive", line 2146, in send
remote:     self.smtp.sendmail(self.envelopesender, to_addrs, msg)
remote:   File "/usr/lib64/python2.6/smtplib.py", line 710, in sendmail
remote:     (code,resp)=self.rcpt(each, rcpt_options)
remote:   File "/usr/lib64/python2.6/smtplib.py", line 465, in rcpt
remote:     return self.getreply()
remote:   File "/usr/lib64/python2.6/smtplib.py", line 342, in getreply
remote:     line = self.file.readline(_MAXLINE + 1)
remote:   File "/usr/lib64/python2.6/socket.py", line 479, in readline
remote:     data = self._sock.recv(self._rbufsize)
remote: timeout: timed out
remote:
Also, the above exception does not occur all the time.

**Comment by moy** [comment]
I guess this happens when the mail server doesn't respond, and trying to send the email times out. If so, there's not much git-multimail can do. Well, obviously, the error message should be more user-friendly but in the end there'll be an error and no email sent.

**Comment by moy** [comment]
I tried making the error message better. Can you test again with `git_multimail.py` from Git's HEAD?

**Comment by hbala2** [comment]
Thanks for your response, I will try this out. Should I also try increasing the value of smtpServerTimeout in the config file. I think the default is 10 seconds.

**Comment by moy** [comment]
Yes, increasing the timeout may help. And yes, the default is 10 (it was undocumented, fixed).
