### ISSUE TITLE
IOError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by develvis** [git-multimail/git-multimail#204]
git-multimail version 1.4.0
Python version 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
[GCC 7.3.0]
Traceback (most recent call last):
  File "/data/git/.gitolite/local/hooks/repo-specific/git_multimail.py", line 4214, in main
    run_as_post_receive_hook(environment, mailer)
  File "/data/git/.gitolite/local/hooks/repo-specific/git_multimail.py", line 3669, in run_as_post_receive_hook
    push.send_emails(mailer, body_filter=environment.filter_body)
  File "/data/git/.gitolite/local/hooks/repo-specific/git_multimail.py", line 3596, in send_emails
    rev.recipients,
  File "/data/git/.gitolite/local/hooks/repo-specific/git_multimail.py", line 2007, in send
    p.stdin.writelines(lines)
IOError: [Errno 32] Broken pipe

**Comment by moy** [comment]
Thanks for the report, but unfortunately I can't debug that without a bit more info. Can you try:

* Upgrading to 1.5.0, just released?

* Setting `multimailhook.smtpServerDebugLevel` to 1, or to a greater value, and see if you get more info

?

This happens when git-multimail sends data to the SMTP server, so it's possible that the issue is on the SMTP side too.

**Comment by develvis** [comment]
I upgraded to 1.5 and set the  multimailhook.smtpServerDebugLevel to a
value of 16. The same response was generated. I have verified using the
sendmail command from the command line works and I have Mantis BugTracker
installed on the same server and it is able to send emails out.

Here are the settings I have within my gitolite-admin configuration.

    option hook.post-receive         =   post-receive
    config multimailhook.smtpServerDebugLevel = 16
    config multimailhook.debugLogFile =
/data/git/.gitolite/logs/multimail.log
    config multimailhook.verbose = true
    config multimailhook.mailingList = rdevelvis@dminc.com
    config multimailhook.from = etims-dev@dminc.com
    config multimailhook.administrator = rdevelvis@dminc.com
    config multimailhook.commitEmailFormat = html

2019-01-18 07:52:38,643 [DEBUG]  run_as_post_receive_hook:
oldrev=369976c59f7f0f6aa0311b5ddd8e603c44bffef3,
newrev=704f3471d975524105531eb8a132bf66f6820e33, refname=refs/heads/master
2019-01-18 07:52:38,652 [INFO ]  Sending notification emails to:
rdevelvis@dminc.com
2019-01-18 07:52:38,679 [ERROR]  *** Error while generating commit email
***  - mail sending aborted.

2019-01-18 07:52:38,681 [ERROR]  Exception 'IOError' raised. Please report
this as a bug to
https://github.com/git-multimail/git-multimail/issues
with the information below:

git-multimail version 1.5.0
Python version 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
[GCC 7.3.0]
Traceback (most recent call last):
  File "/data/git/.gitolite/local/hooks/repo-specific/git_multimail.py",
line 4321, in main
    run_as_post_receive_hook(environment, mailer)
  File "/data/git/.gitolite/local/hooks/repo-specific/git_multimail.py",
line 3772, in run_as_post_receive_hook
    push.send_emails(mailer, body_filter=environment.filter_body)
  File "/data/git/.gitolite/local/hooks/repo-specific/git_multimail.py",
line 3693, in send_emails
    rev.recipients,
  File "/data/git/.gitolite/local/hooks/repo-specific/git_multimail.py",
line 2052, in send
    p.stdin.writelines(lines)
IOError: [Errno 32] Broken pipe
