### ISSUE TITLE
Error while generating commit email

### ISSUE THREAD

**Issue by DJ-Andrey-sXe** [git-multimail/git-multimail#206]
Using:

on  developer's machine:
git version 2.22.0.windows.1 on Win 10

on server (hosts repo with ssh access on Ubuntu 12.04.5):
git version 1.7.9.5

after push:

Enumerating objects: 26, done.
Counting objects: 100% (26/26), done.
Delta compression using up to 2 threads
Compressing objects: 100% (13/13), done.
Writing objects: 100% (14/14), 2.93 KiB | 998.00 KiB/s, done.
Total 14 (delta 9), reused 0 (delta 0)
remote: Sending notification emails to: *******
remote: *** Error while generating commit email
remote: ***  - mail sending aborted.
remote: Exception 'UnicodeDecodeError' raised. Please report this as a bug to
remote: https://github.com/git-multimail/git-multimail/issues
remote: with the information below:
remote: git-multimail version 1.4.0
remote: Python version 2.7.3 (default, Oct 26 2016, 21:04:23)
remote: [GCC 4.6.3]
remote: Traceback (most recent call last):
remote:   File "hooks/post-receive", line 4214, in main
remote:     run_as_post_receive_hook(environment, mailer)
remote:   File "hooks/post-receive", line 3669, in run_as_post_receive_hook
remote:     push.send_emails(mailer, body_filter=environment.filter_body)
remote:   File "hooks/post-receive", line 3596, in send_emails
remote:     rev.recipients,
remote:   File "hooks/post-receive", line 2007, in send
remote:     p.stdin.writelines(lines)
remote:   File "hooks/post-receive", line 2006, in <genexpr>
remote:     lines = (str_to_bytes(line) for line in lines)
remote:   File "hooks/post-receive", line 1739, in generate_combined_email
remote:     for line in self.generate_email(push, body_filter, values):
remote:   File "hooks/post-receive", line 958, in generate_email
remote:     for line in self.generate_email_header(**extra_header_values):
remote:   File "hooks/post-receive", line 1337, in generate_email_header
remote:     self.header_template, **extra_values
remote:   File "hooks/post-receive", line 889, in expand_header_lines
remote:     value = header_encode(value, name)
remote:   File "hooks/post-receive", line 522, in header_encode
remote:     text = unicode(text, 'utf-8')
remote: UnicodeDecodeError: 'utf8' codec can't decode byte 0xd1 in position 525: invalid continuation byte

Commit message was:

"ЛК.
1. Если пользователь ввёл неправильную пару логин-пароль,
   ему кроме этого факта выдаётся:
   a) ссылка на восстановление пароля
   б) подсказка, что вход доступен только зарегистрированным
   в) ссылка на регистрацию
   г) напоминание, что пароль при регистрации высылается по СМС
2. Новая страница для сотрудников: переплата"

There are successful commits in the past with messages in russian, for example "ЛК. При регистрации родителя email - обязательное поле.", and much longer and multiline, and they pushed ok, but this notification failed. I can't find consistent pattern in commit message that call the error. Please help. Maybe I should try to update something on server side?

**Comment by moy** [comment]
Can you try using python 3?

Le 10 septembre 2019 15:54:31 GMT+02:00, DJ-Andrey-sXe <notifications@github.com> a écrit :
>Using:
>
>on  developer's machine:
>git version 2.22.0.windows.1 on Win 10
>
>on server (hosts repo with ssh access on Ubuntu 12.04.5):
>git version 1.7.9.5
>
>after push:
>
>Enumerating objects: 26, done.
>Counting objects: 100% (26/26), done.
>Delta compression using up to 2 threads
>Compressing objects: 100% (13/13), done.
>Writing objects: 100% (14/14), 2.93 KiB | 998.00 KiB/s, done.
>Total 14 (delta 9), reused 0 (delta 0)
>remote: Sending notification emails to: *******
>remote: *** Error while generating commit email
>remote: ***  - mail sending aborted.
>remote: Exception 'UnicodeDecodeError' raised. Please report this as a
>bug to
>remote: https://github.com/git-multimail/git-multimail/issues
>remote: with the information below:
>remote: git-multimail version 1.4.0
>remote: Python version 2.7.3 (default, Oct 26 2016, 21:04:23)
>remote: [GCC 4.6.3]
>remote: Traceback (most recent call last):
>remote:   File "hooks/post-receive", line 4214, in main
>remote:     run_as_post_receive_hook(environment, mailer)
>remote:   File "hooks/post-receive", line 3669, in
>run_as_post_receive_hook
>remote:     push.send_emails(mailer,
>body_filter=environment.filter_body)
>remote:   File "hooks/post-receive", line 3596, in send_emails
>remote:     rev.recipients,
>remote:   File "hooks/post-receive", line 2007, in send
>remote:     p.stdin.writelines(lines)
>remote:   File "hooks/post-receive", line 2006, in <genexpr>
>remote:     lines = (str_to_bytes(line) for line in lines)
>remote:   File "hooks/post-receive", line 1739, in
>generate_combined_email
>remote:     for line in self.generate_email(push, body_filter, values):
>remote:   File "hooks/post-receive", line 958, in generate_email
>remote:     for line in
>self.generate_email_header(**extra_header_values):
>remote:   File "hooks/post-receive", line 1337, in
>generate_email_header
>remote:     self.header_template, **extra_values
>remote:   File "hooks/post-receive", line 889, in expand_header_lines
>remote:     value = header_encode(value, name)
>remote:   File "hooks/post-receive", line 522, in header_encode
>remote:     text = unicode(text, 'utf-8')
>remote: UnicodeDecodeError: 'utf8' codec can't decode byte 0xd1 in
>position 525: invalid continuation byte
>
>Commit message was:
>
>"ЛК.
>1. Если пользователь ввёл неправильную пару логин-пароль,
>   ему кроме этого факта выдаётся:
>   a) ссылка на восстановление пароля
>   б) подсказка, что вход доступен только зарегистрированным
>   в) ссылка на регистрацию
>   г) напоминание, что пароль при регистрации высылается по СМС
>2. Новая страница для сотрудников: переплата"
>
>There are successful commits in the past with messages in russian, for
>example "ЛК. При регистрации родителя email - обязательное поле.", and
>much longer and multiline, and they pushed ok, but this notification
>failed. I can't find consistent pattern in commit message that call the
>error. Please help. Maybe I should try to update something on server
>side?
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/git-multimail/git-multimail/issues/206

-- 
Envoyé de mon telephone. Veuillez excuser ma brièveté.
